//<![CDATA[
$(window).load(function(){$(".spinner-wrap").fadeOut(),$("#PreLoader").delay(350).fadeOut("slow"),$("body").delay(350).css({overflow:"visible"})});
//
$(document).ready(function()
{
if($("#mycredit").attr("href")!="http://www.blogcozone.com/")
{
window.location.href="http://www.blogcozone.com";
}
});
//]]>